# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        # reduce set of ruby to validate min and max to reduce compute waste.
        #  min: 2.7 - nobody uses 2.5 or 2.6 anymore
        #  max: 3.4 - 3.4 is the latest stable release
        #  intermediate version 3.0, 3.1, 3.2 don't have much value compared the latest.
        ruby-version: [2.7] # head temporarily removed to reduce compute waste
        # ruby-version: [2.5, 2.6, 2.7, '3.0', 3.1, 3.2, head, debug, truffleruby]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v3
    - name: Enable Rosetta (macOS only)
      if: matrix.os == 'macos'
      run: |
        softwareupdate --install-rosetta --agree-to-license
    - name: Install libcurl header
      run: |
        if ${{ matrix.os == 'macos' }}
        then
          arch -x86_64 brew install curl libidn2 rtmpdump zstd
        else
          sudo apt update && sudo apt install -y --no-install-recommends libcurl4-openssl-dev
        fi
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Print ruby version
      run: ruby -v
    - name: Run tests
      # Use arch -x86_64 for macOS to ensure compatibility with some gems that may not support ARM architecture
      run: |
        if ${{ matrix.os == 'macos' }}
        then
          arch -x86_64 bundle exec rake
        else
          bundle exec rake
        fi
